
language: node_js

node_js:
  - "10"

cache:
  directories:
    - "node_modules"

script:
    - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: public
  target-branch: master
  on:
    branch: source
